esphome:
  name: serialsentinel
  friendly_name: Serial Sentinel

esp32:
  board: esp32-c3-devkitm-1

# Enable logging
logger:
  hardware_uart: UART0

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SerialSentinel Fallback Hotspot"
    password: "serial123"

captive_portal:

# Web server for debugging and manual control
web_server:
  port: 80

# I2C Bus Configuration
i2c:
  sda: GPIO18
  scl: GPIO10
  scan: true

# UART Configuration
uart:
  # External UART on GPIO3/4
  - tx_pin: GPIO4
    rx_pin: GPIO3
    baud_rate: 115200
    id: uart_bus
  

# Output definitions
output:
  # LED outputs
  - platform: gpio
    pin: GPIO0
    id: led1_output
  
  - platform: gpio
    pin: GPIO7
    id: led2_output
  
  # Wake output
  - platform: gpio
    pin: GPIO19
    id: wake_output
  
  # Relay outputs (default off)
  - platform: gpio
    pin: GPIO5
    id: relay1_output
    inverted: false
  
  - platform: gpio
    pin: GPIO6
    id: relay2_output
    inverted: false

# Switch definitions for easy control
switch:
  # LED switches
  - platform: output
    name: "LED1"
    output: led1_output
    id: led1_switch
  
  - platform: output
    name: "LED2"
    output: led2_output
    id: led2_switch
  
  # Wake switch
  - platform: output
    name: "Wake Signal"
    output: wake_output
    id: wake_switch
  
  # Relay switches
  - platform: output
    name: "Relay 1"
    output: relay1_output
    id: relay1_switch
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: output
    name: "Relay 2"
    output: relay2_output
    id: relay2_switch
    restore_mode: RESTORE_DEFAULT_OFF

